title: VISC
description: バリアント情報標準化研究会（Variant Information Standardization Collegium）
theme: minima

# プロジェクトサイト配信
baseurl: "/visc"
url: "https://dbcls.github.io"

# コレクション定義
collections:
  meetings:
    output: true
    permalink: /meetings/:name/
  projects:
    output: true
    permalink: /projects/:name/
  people:
    output: true
    permalink: /members/:name/
  publications:
    output: true
    permalink: /publications/:name/

# ヘッダーメニュー
#header_pages:
#  - meetings.md
#  - projects.md
#  - databases.md
#  - publications.md
#  - members.md
#  - join.md
#  - news.md
#  - about.md

# 除外
exclude:
  - README.md
